### ISSUE TITLE
Broken FAQ site

### ISSUE THREAD

**Issue by fhtino** [stuartd/keymapper#14] opened 2018-06-27 16:46 UTC
http://justkeepswimming.net/keymapper/faq.aspx

broken? dead?

**Comment by stuartd** [comment] 2018-06-27 17:54
Oh right, yes on the help dialogue? I gave that domain up years ago. I'll take it out for the next release (which hopefully will be in less than 10 years, as that's when the last one was!)

**Comment by stuartd** [comment] 2018-06-27 17:56
It's [available on the Internet Archive](https://web.archive.org/web/20150923172252/http://justkeepswimming.net:80/keymapper/faq.aspx)

**Comment by fhtino** [comment] 2018-06-27 18:03
OK. But, don't worry. I was able to use keymapper without the FAQ.
Suggestion: create a .MD file on you github repo and copy-paste old FAQ.  Somebody could be interested. You can even change the old link to this new one.

**Comment by stuartd** [comment] 2018-06-27 18:04
Yeah, I will do that, thanks. I see the FAQ needs a bit of updating.. As I don't own that domain any more I can't redirect here, though.

**Comment by yestalgia** [comment] 2018-12-10 05:13
I think he means set the link in the program to direct users here.

**Comment by stuartd** [comment] 2018-12-10 10:56
Yes. And when I do a new release, I will.

**Comment by Aoxo** [comment] 2019-09-01 01:10
This link should be removed as it has now been hijacked, possibly for distribution of malware.  It redirects me to "http://iyfnzgb.com/?pid=9PO1H9V71&dn=justkeepswimming.net" and tells me to run some kind of scan then install something in the mozilla store.

**Comment by stuartd** [comment] 2019-09-02 09:40
You're right, and I'll do a build of the latest version and put it up as a release.

The trouble is that the link is hardcoded in the EXE file, so I cannot do anything about existing downloads.

**Comment by Aoxo** [comment] 2019-09-02 09:49
Thank you!  I really appreciate your program and your response.  I'm a
gamer and I was looking to use capslock as a push to talk key, but it would
obviously toggle caps and cause me to start "yelling" in text
conversations.  I'm not a fan of capslock because I think it causes more
problems than it solves.  For now I have mapped it to scroll lock, but I
still have a status light going on or off each time I use push to talk.  I
can live with that but I was hoping to use a mostly unused, non-printing
key like pause/break instead.

Thanks again!

**Comment by Aoxo** [comment] 2019-09-02 10:00
Oh...so there's no way to map capslock to the break key and have it press
and release the break key when I press and release capslock?

**Comment by stuartd** [comment] 2019-09-02 10:12
Thanks for your kind words, much appreciated. 

You can't do what you want with AutoMapper, sorry. It tells Windows "hey, this key is Pause now" and it acts just like the real Pause key does (note that [Pause/break is a weird outlier as far as keys are concerned anyway](https://web.archive.org/web/20150923172252/http://justkeepswimming.net:80/keymapper/faq.aspx#q25) - full details of why are [here](https://www.neox.net/w/2008/02/13/keyboard-remap-pause-break-key-as-del-key/))

(Incidentally, it was because I wanted to turn CapsLock off and NumLock on that I started looking into keyboard mappings, which got me started on developing KeyMapper!)

As I said in #17, AutoHotKey is worth a try for your requirements, noting the weirdness above about Pause/Break.

**Comment by Aoxo** [comment] 2019-09-02 10:27
I'm sorry to keep dragging on and at the risk of asking the same question
over and over, I just want to make sure I'm conveying what I'm trying to do
properly and that I'm understanding what you're telling me.

I would like to map capslock to pause/break so that pressing capslock does
the same thing that pressing pause/break does.  The problem is when I have
it mapped and press and then release capslock, it locks pause/break as if
it's in a keydown position.  Only pressing the real pause/break key
triggers the keyup.  I would like for capslock to act exactly like the
pause break key, and less like a "lock" key.

Sorry I don't mean to be a pest.

**Comment by stuartd** [comment] 2019-09-02 12:07
I can't really help here, sorry. I suspect it's related to the weirdness of the Pause/Break key - from https://devblogs.microsoft.com/oldnewthing/?p=23503  

> In the original PC/XT keyboard layout, there was no Break key. The key sequence for Break was Ctrl+ScrollLock. (And for completeness, the key sequence for Pause was Ctrl+NumLock.) Even though the enhanced keyboard moved the Pause and Break functions to their own key, pressing the Pause key internally generated scan codes that simulated a press of Ctrl+NumLock. In other words, when you pressed Pause, the keyboard hardware actually tells the computer, “The user pressed the Ctrl key and then pressed the NumLock key.” Similarly, when you pressed Ctrl+Break, the keyboard hardware tells the computer, “The user pressed the Ctrl key and then pressed the ScrollLock key.”

Have you tried AutoHotKey?

**Closed** 2024-06-10 13:35 UTC
Labels: bug
